name: CD

on:
  workflow_run:
    workflows: ["CI"]   # trigger after CI finishes
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # only run if CI passed
    runs-on: self-hosted   # needs a self-hosted runner (EC2, VM, etc.)

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/flask-aws-starter-APP-DEV:latest
          docker pull $IMAGE_NAME

      - name: Stop and remove old container
        run: |
          docker ps -q --filter "name=flask-aws-starter-APP-DEV" | grep -q . && docker stop flask-aws-starter-APP-DEV && docker rm flask-aws-starter-APP-DEV || echo "No old container"

      - name: Run new container
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/flask-aws-starter-APP-DEV:latest
          docker run -d --name flask-aws-starter-APP-DEV -p 80:5000 $IMAGE_NAME
